-- healthy-living: table + RLS + seed. Paste into the Supabase SQL editor (shared damlahelloworld project).
create table if not exists hl_entries (
  id uuid primary key default gen_random_uuid(),
  kind text not null check (kind in ('link','exercise')),
  category text not null check (category in ('healthy-living-articles','home-workouts','pilates','ballet','yoga','gym','calisthenics','bodyweight')),
  title text not null check (char_length(title) between 2 and 200),
  url text check (url is null or url ~* '^https?://'),
  description text check (description is null or char_length(description) <= 500),
  contributor text not null check (char_length(contributor) between 1 and 60),
  recommend_count int not null default 1,
  approved boolean not null default false,
  created_at timestamptz not null default now()
);
alter table hl_entries enable row level security;
drop policy if exists hl_public_read on hl_entries;
create policy hl_public_read on hl_entries for select using (approved = true);
drop policy if exists hl_anon_suggest on hl_entries;
create policy hl_anon_suggest on hl_entries for insert with check (approved = false and recommend_count = 1);

insert into hl_entries (kind, category, title, url, description, contributor, recommend_count, approved) values
('link','healthy-living-articles','Diaphragmatic Breathing','https://my.clevelandclinic.org/health/articles/9445-diaphragmatic-breathing','Cleveland Clinic','damla',1,true),
('link','healthy-living-articles','How To Do the 4-7-8 Breathing Exercise','https://health.clevelandclinic.org/4-7-8-breathing','Cleveland Clinic','damla',1,true),
('link','healthy-living-articles','Why good posture matters','https://www.health.harvard.edu/staying-healthy/why-good-posture-matters','Harvard Health Publishing','damla',1,true),
('link','healthy-living-articles','Pilates 101: What It Is and Health Benefits','https://health.clevelandclinic.org/everything-you-want-to-know-about-pilates','Cleveland Clinic','damla',1,true),
('link','healthy-living-articles','Habit Formation: How Long It Takes and How to Start Now','https://www.healthline.com/health/how-long-does-it-take-to-form-a-habit','Healthline','damla',1,true),
('link','healthy-living-articles','Exercising to relax','https://www.health.harvard.edu/staying-healthy/exercising-to-relax','Harvard Health Publishing','damla',1,true),
('link','healthy-living-articles','Exercise is an all-natural treatment to fight depression','https://www.health.harvard.edu/mind-and-mood/exercise-is-an-all-natural-treatment-to-fight-depression','Harvard Health Publishing','damla',1,true),
('link','healthy-living-articles','Strength training builds more than muscles','https://www.health.harvard.edu/staying-healthy/strength-training-builds-more-than-muscles','Harvard Health Publishing','damla',1,true),
('link','healthy-living-articles','Physical activity','https://www.who.int/news-room/fact-sheets/detail/physical-activity','World Health Organization','damla',1,true),
('link','healthy-living-articles','Delayed Onset Muscle Soreness (DOMS): What It Is & Treatment','https://my.clevelandclinic.org/health/diseases/delayed-onset-muscle-soreness','Cleveland Clinic','damla',1,true),
('link','healthy-living-articles','How To Make the Most Out of Active Recovery','https://health.clevelandclinic.org/active-recovery','Cleveland Clinic','damla',1,true),
('link','healthy-living-articles','Walking for health','https://www.nhs.uk/live-well/exercise/walking-for-health/','NHS','damla',1,true),
('link','healthy-living-articles','5 surprising benefits of walking','https://www.health.harvard.edu/stay-healthy/5-surprising-benefits-of-walking','Harvard Health Publishing','damla',1,true),
('link','healthy-living-articles','Exercise and Sleep','https://www.sleepfoundation.org/physical-activity/exercise-and-sleep','Sleep Foundation','damla',1,true),
('link','healthy-living-articles','The importance of stretching','https://www.health.harvard.edu/staying-healthy/the-importance-of-stretching','Harvard Health Publishing','damla',1,true),
('link','healthy-living-articles','Benefits of exercise','https://www.nhs.uk/live-well/exercise/exercise-health-benefits/','NHS','damla',1,true),
('exercise','pilates','Wall Glute Bridge','https://www.bustle.com/wellness/beginner-wall-pilates-exercises','beginner · wall, mat','damla',1,true),
('exercise','pilates','Wall Hundred','https://www.bustle.com/wellness/beginner-wall-pilates-exercises','intermediate · wall, mat','damla',1,true),
('exercise','pilates','Wall Bicycle Crunch','https://www.bustle.com/wellness/beginner-wall-pilates-exercises','intermediate · wall, mat','damla',1,true),
('exercise','pilates','Wall Sit','https://www.bustle.com/wellness/beginner-wall-pilates-exercises','beginner · wall','damla',1,true),
('exercise','pilates','Wall-Supported Lunge','https://www.bustle.com/wellness/beginner-wall-pilates-exercises','intermediate · wall','damla',1,true),
('exercise','pilates','Standing Wall Leg Lift','https://www.bustle.com/wellness/beginner-wall-pilates-exercises','beginner · wall','damla',1,true),
('exercise','pilates','Wall Side Kick','https://www.bustle.com/wellness/beginner-wall-pilates-exercises','beginner · wall','damla',1,true),
('exercise','pilates','Wall Leg Circles','https://www.bustle.com/wellness/beginner-wall-pilates-exercises','beginner · wall','damla',1,true),
('exercise','pilates','Wall Roll Down','https://www.bustle.com/wellness/beginner-wall-pilates-exercises','beginner · wall','damla',1,true),
('exercise','pilates','Wall Push-Up','https://www.bustle.com/wellness/beginner-wall-pilates-exercises','beginner · wall','damla',1,true),
('exercise','pilates','Pelvic Curl','https://www.basipilates.com/pilates/10-essential-pilates-exercises-for-beginners/','beginner · mat','damla',1,true),
('exercise','pilates','Chest Lift','https://www.basipilates.com/pilates/10-essential-pilates-exercises-for-beginners/','beginner · mat','damla',1,true),
('exercise','pilates','Chest Lift with Rotation','https://www.basipilates.com/pilates/10-essential-pilates-exercises-for-beginners/','intermediate · mat','damla',1,true),
('exercise','pilates','Spine Twist Supine','https://www.basipilates.com/pilates/10-essential-pilates-exercises-for-beginners/','beginner · mat','damla',1,true),
('exercise','pilates','Single Leg Stretch','https://www.basipilates.com/pilates/10-essential-pilates-exercises-for-beginners/','intermediate · mat','damla',1,true),
('exercise','pilates','Roll Up','https://www.basipilates.com/pilates/10-essential-pilates-exercises-for-beginners/','intermediate · mat','damla',1,true),
('exercise','pilates','Rolling Like a Ball','https://www.basipilates.com/pilates/10-essential-pilates-exercises-for-beginners/','intermediate · mat','damla',1,true),
('exercise','pilates','Single Leg Circles','https://www.basipilates.com/pilates/10-essential-pilates-exercises-for-beginners/','intermediate · mat','damla',1,true),
('exercise','pilates','All Fours (Quadruped Balance)','https://www.basipilates.com/pilates/10-essential-pilates-exercises-for-beginners/','beginner · mat','damla',1,true),
('exercise','pilates','Back Extension','https://www.basipilates.com/pilates/10-essential-pilates-exercises-for-beginners/','beginner · mat','damla',1,true),
('exercise','home-workouts','Sit to Stand','https://www.nhs.uk/live-well/exercise/strength-exercises/','beginner · chair','damla',1,true),
('exercise','home-workouts','Supported Mini Squat','https://www.nhs.uk/live-well/exercise/strength-exercises/','beginner · chair','damla',1,true),
('exercise','home-workouts','Calf Raise','https://www.nhs.uk/live-well/exercise/strength-exercises/','beginner · chair','damla',1,true),
('exercise','home-workouts','Sideways Leg Lift','https://www.nhs.uk/live-well/exercise/strength-exercises/','beginner · chair','damla',1,true),
('exercise','home-workouts','Standing Leg Extension','https://www.nhs.uk/live-well/exercise/strength-exercises/','beginner · chair','damla',1,true),
('exercise','home-workouts','Water Bottle Bicep Curl','https://www.nhs.uk/live-well/exercise/strength-exercises/','beginner · water bottle','damla',1,true),
('exercise','home-workouts','Seated Upright Row with Bottles','https://www.bhf.org.uk/informationsupport/heart-matters-magazine/activity/strength-exercises','beginner · chair, water bottle','damla',1,true),
('exercise','home-workouts','Chair Dip','https://www.healthline.com/health/chair-dips','intermediate · chair','damla',1,true),
('exercise','home-workouts','Towel Glute Bridge and Curl','https://redefiningstrength.com/5-towel-exercises-full-body-workout/','intermediate · mat, towel','damla',1,true),
('exercise','home-workouts','Towel Sliding Side Lunge','https://redefiningstrength.com/5-towel-exercises-full-body-workout/','intermediate · towel','damla',1,true),
('exercise','home-workouts','Marching in Place','https://health.clevelandclinic.org/is-walking-in-place-exercise','beginner · no equipment','damla',1,true),
('exercise','home-workouts','Low Impact Jumping Jack','https://www.healthline.com/health/fitness-exercise/low-impact-cardio','beginner · no equipment','damla',1,true),
('exercise','home-workouts','Speed Skater (Step Version)','https://www.healthline.com/health/fitness-exercise/low-impact-cardio','intermediate · no equipment','damla',1,true),
('exercise','home-workouts','Squat to Jab','https://www.healthline.com/health/fitness-exercise/low-impact-cardio','intermediate · no equipment','damla',1,true),
('exercise','home-workouts','Standing Oblique Crunch','https://www.healthline.com/health/fitness-exercise/low-impact-cardio','beginner · no equipment','damla',1,true),
('exercise','home-workouts','Lateral Shuffle','https://www.healthline.com/health/fitness-exercise/low-impact-cardio','beginner · no equipment','damla',1,true),
('exercise','home-workouts','Reverse Lunge Front Kick','https://www.healthline.com/health/fitness-exercise/low-impact-cardio','intermediate · no equipment','damla',1,true),
('exercise','home-workouts','Cat-Cow Stretch','https://health.clevelandclinic.org/cat-cow-stretch','beginner · mat','damla',1,true),
('exercise','home-workouts','Hamstring Stretch','https://www.healthline.com/health/full-body-stretch','beginner · mat','damla',1,true),
('exercise','home-workouts','Calf Stretch','https://www.healthline.com/health/full-body-stretch','beginner · wall','damla',1,true),
('exercise','home-workouts','Standing Quadriceps Stretch','https://www.healthline.com/health/full-body-stretch','beginner · wall','damla',1,true),
('exercise','home-workouts','Glute Stretch','https://www.healthline.com/health/full-body-stretch','beginner · mat','damla',1,true),
('exercise','home-workouts','Chest Stretch','https://www.healthline.com/health/full-body-stretch','beginner · wall','damla',1,true),
('exercise','home-workouts','Upper Back Stretch','https://www.healthline.com/health/full-body-stretch','beginner · no equipment','damla',1,true),
('exercise','home-workouts','Neck Circles','https://www.healthline.com/health/full-body-stretch','beginner · no equipment','damla',1,true);
