import Foundation

struct FoodNameSuggester {
    static let knownFoods: [String] = [
        // Protein sources
        "chicken breast",
        "chicken thigh",
        "grilled chicken",
        "ground beef",
        "ground turkey",
        "beef steak",
        "sirloin steak",
        "ribeye steak",
        "salmon",
        "tuna",
        "canned tuna",
        "shrimp",
        "tilapia",
        "cod",
        "turkey breast",
        "pork chop",
        "pork tenderloin",
        "bacon",
        "sausage",
        "egg",
        "egg white",
        "boiled egg",
        "scrambled egg",
        "whey protein",
        "protein bar",
        "greek yogurt",
        "cottage cheese",
        "tofu",
        "tempeh",

        // Dairy
        "milk",
        "whole milk",
        "skim milk",
        "almond milk",
        "oat milk",
        "cheese",
        "cheddar cheese",
        "mozzarella",
        "parmesan",
        "cream cheese",
        "butter",
        "yogurt",

        // Grains & Carbs
        "white rice",
        "brown rice",
        "jasmine rice",
        "basmati rice",
        "oatmeal",
        "oats",
        "pasta",
        "spaghetti",
        "penne",
        "macaroni",
        "bread",
        "white bread",
        "whole wheat bread",
        "sourdough bread",
        "tortilla",
        "bagel",
        "english muffin",
        "pancake",
        "waffle",
        "cereal",
        "granola",
        "quinoa",
        "couscous",
        "bulgur",
        "noodles",
        "ramen",

        // Fruits
        "banana",
        "apple",
        "orange",
        "strawberry",
        "blueberry",
        "raspberry",
        "grape",
        "watermelon",
        "mango",
        "pineapple",
        "peach",
        "pear",
        "kiwi",
        "avocado",
        "cherry",
        "lemon",
        "lime",
        "pomegranate",
        "fig",
        "date",

        // Vegetables
        "broccoli",
        "spinach",
        "kale",
        "lettuce",
        "tomato",
        "cucumber",
        "carrot",
        "bell pepper",
        "onion",
        "garlic",
        "mushroom",
        "zucchini",
        "sweet potato",
        "potato",
        "corn",
        "green beans",
        "asparagus",
        "cauliflower",
        "celery",
        "cabbage",
        "eggplant",
        "peas",

        // Nuts & Seeds
        "almond",
        "peanut",
        "walnut",
        "cashew",
        "pistachio",
        "peanut butter",
        "almond butter",
        "sunflower seeds",
        "chia seeds",
        "flax seeds",
        "mixed nuts",
        "trail mix",

        // Snacks & Sweets
        "protein shake",
        "smoothie",
        "energy bar",
        "granola bar",
        "dark chocolate",
        "chocolate",
        "ice cream",
        "cookie",
        "brownie",
        "cake",
        "donut",
        "chips",
        "popcorn",
        "crackers",
        "rice cake",
        "hummus",

        // Common meals
        "salad",
        "chicken salad",
        "caesar salad",
        "soup",
        "chicken soup",
        "lentil soup",
        "sandwich",
        "burger",
        "pizza",
        "wrap",
        "burrito",
        "taco",
        "sushi",
        "stir fry",
        "fried rice",
        "curry",
        "chili",
        "omelet",

        // Drinks
        "coffee",
        "black coffee",
        "latte",
        "cappuccino",
        "tea",
        "green tea",
        "orange juice",
        "apple juice",
        "protein water",
        "coconut water",
        "soda",
        "sparkling water",

        // Turkish common foods
        "pilav",
        "bulgur pilavi",
        "mercimek corbasi",
        "tavuk gogsu",
        "kofte",
        "lahmacun",
        "pide",
        "simit",
        "borek",
        "su boregi",
        "sigara boregi",
        "menemen",
        "sucuk",
        "kasarli tost",
        "ayran",
        "cacik",
        "ezme",
        "kisir",
        "dolma",
        "sarma",
        "iskender",
        "doner",
        "adana kebab",
        "urfa kebab",
        "beyti",
        "cig kofte",
        "baklava",
        "kunefe",
        "sutlac",
        "lokum",
        "pogaca",
        "acma",
    ]

    static func suggestions(for input: String) -> [String] {
        let cleaned = input.lowercased().trimmingCharacters(in: .whitespaces)
        guard cleaned.count >= 2 else { return [] }

        var prefixMatches: [String] = []
        var containsMatches: [String] = []

        for name in knownFoods {
            if name.hasPrefix(cleaned) {
                prefixMatches.append(name)
            } else if name.contains(cleaned) {
                containsMatches.append(name)
            }
        }

        return Array((prefixMatches.sorted() + containsMatches.sorted()).prefix(5))
    }
}
